# nixy listening port
port = "8081"
# optional X-Proxy header name
xproxy = "hostname"
# marathon api
user = "" # leave empty if no auth is required.
pass = ""
# nginx
nginx_config = "/etc/nginx/nginx.conf"
nginx_template = "/etc/nginx/nginx.tmpl"
nginx_cmd = "nginx" # optionally openresty
